spring.application.name=Sistema-Escolar
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sistema-escolar-db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

api.sistema-escolar.auth.token.secret=${AUTH_TOKEN_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:default_username}
spring.mail.password=${MAIL_PASSWORD:default_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

springdoc.override-with-generic-response=false
