-- Schema inicial do Sistema Escolar (equivalente ao que o Hibernate gerava com ddl-auto=update)

create table tb_disciplina (
    id   bigint generated by default as identity primary key,
    nome varchar(255)
);

create table tb_usuario (
    id                        bigint generated by default as identity primary key,
    dtype                     varchar(31)  not null,
    nome                      varchar(255) not null,
    sobrenome                 varchar(255) not null,
    email                     varchar(255) not null,
    senha                     varchar(255) not null,
    role                      varchar(255) not null check (role in ('ADMIN', 'PROFESSOR', 'ESTUDANTE')),
    verificado                boolean,
    codigo_de_verificacao     varchar(255),
    tempo_de_expiracao_codigo timestamp(6),
    professor_disciplina_id   bigint,
    constraint fk_usuario_professor_disciplina foreign key (professor_disciplina_id) references tb_disciplina
);

create table tb_redefinir_senha (
    id                        bigint generated by default as identity primary key,
    codigo_de_verificacao     varchar(255) not null,
    tempo_de_expiracao_codigo timestamp(6) not null,
    usuario_id                bigint,
    constraint fk_redefinir_senha_usuario foreign key (usuario_id) references tb_usuario
);

create table tb_turma (
    id                     bigint generated by default as identity primary key,
    nome                   varchar(255) not null,
    codigo_turma           varchar(255),
    tempo_expiracao_codigo timestamp(6),
    disciplina_id          bigint,
    professor_id           bigint,
    constraint fk_turma_disciplina foreign key (disciplina_id) references tb_disciplina,
    constraint fk_turma_professor foreign key (professor_id) references tb_usuario
);

create table estudante_turma (
    estudante_id bigint not null,
    turma_id     bigint not null,
    constraint fk_estudante_turma_estudante foreign key (estudante_id) references tb_usuario,
    constraint fk_estudante_turma_turma foreign key (turma_id) references tb_turma
);

create table estudante_disciplina (
    estudante_id  bigint not null,
    disciplina_id bigint not null,
    constraint fk_estudante_disciplina_estudante foreign key (estudante_id) references tb_usuario,
    constraint fk_estudante_disciplina_disciplina foreign key (disciplina_id) references tb_disciplina
);

create table tb_questao (
    id               bigint generated by default as identity primary key,
    pergunta         varchar(255)   not null,
    tipo_questao     varchar(255) check (tipo_questao in ('OBJETIVA', 'SUBJETIVA', 'VERDADEIRO_FALSO')),
    resposta_correta varchar(255),
    valor            numeric(38, 2) not null,
    criado_por       varchar(255),
    atualizado_por   varchar(255)
);

create table alternativas_questao (
    questao_id   bigint not null,
    alternativas varchar(255),
    constraint fk_alternativas_questao_questao foreign key (questao_id) references tb_questao
);

create table tb_prova (
    id                 bigint generated by default as identity primary key,
    valor_total        numeric(38, 2) not null,
    publicado          boolean,
    tempo_de_expiracao timestamp(6),
    email_professor    varchar(255),
    disciplina_id      bigint,
    constraint fk_prova_disciplina foreign key (disciplina_id) references tb_disciplina
);

create table prova_questao (
    prova_id   bigint not null,
    questao_id bigint not null,
    constraint fk_prova_questao_prova foreign key (prova_id) references tb_prova,
    constraint fk_prova_questao_questao foreign key (questao_id) references tb_questao
);

create table tb_resposta_prova (
    id           bigint generated by default as identity primary key,
    resposta     varchar(255) not null,
    nota         numeric(38, 2),
    avaliada     boolean,
    respondida   boolean,
    estudante_id bigint       not null,
    prova_id     bigint       not null,
    questao_id   bigint       not null,
    constraint fk_resposta_prova_estudante foreign key (estudante_id) references tb_usuario,
    constraint fk_resposta_prova_prova foreign key (prova_id) references tb_prova,
    constraint fk_resposta_prova_questao foreign key (questao_id) references tb_questao
);

create table tb_nota (
    id           bigint generated by default as identity primary key,
    valor        numeric(38, 2),
    estudante_id bigint,
    prova_id     bigint,
    constraint fk_nota_estudante foreign key (estudante_id) references tb_usuario,
    constraint fk_nota_prova foreign key (prova_id) references tb_prova
);
